server:
  port: 8080 # 服务器端口配置
spring:
  jmx:
    enabled: true # 启用JMX监控
  boot:
    admin:
      client:
        url: 'http://localhost:8080' # Spring Boot Admin客户端注册地址

management:
  endpoints:
    enabled-by-default: true # 默认启用所有管理端点
    web:
      base-path: /manage # 管理端点的基础路径
      exposure:
        include: '*' # 暴露所有管理端点

logging:
  file:
    name: 'pdai-spring-boot-application.log' # 日志文件名称
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx' # 日志输出格式
