server:
  port: 8080 # 服务器端口配置
spring:
  datasource: # 数据源配置
    url: jdbc:mysql://8.137.114.181:3306/test_db?useSSL=false&autoReconnect=true&characterEncoding=utf8 # MySQL数据库连接URL
    driver-class-name: com.mysql.jdbc.Driver # MySQL驱动类名
    username: root # 数据库用户名
    password: Tang@123456789 # 数据库密码

mybatis: # MyBatis配置
  mapper-locations: classpath:mybatis/mapper/*.xml # Mapper XML文件位置
  type-aliases-package: tech.pdai.springboot.mysql57.xml.entity # 实体类包路径
  configuration: # MyBatis详细配置
    cache-enabled: false # 启用缓存
    use-generated-keys: true # 使用生成的主键
    default-executor-type: REUSE # 默认执行器类型
    use-actual-param-name: true # 使用实际参数名

knife4j: # Knife4j Swagger增强配置
  enable: true # 启用Knife4j
  setting:
    # default lang
    language: en-US # 默认语言
    # footer
    enableFooter: false # 是否启用页脚
    enableFooterCustom: true # 是否启用自定义页脚
    footerCustomContent: MIT | [Java 全栈](https://pdai.tech) # 自定义页脚内容
    # models
    enableSwaggerModels: true # 是否启用Swagger模型
    swaggerModelName: My Models # Swagger模型名称
